main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
        path("", views.index, name="index"),
        path("write", views.write, name="write"),
    ]

myupweb/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include

urlpatterns = [
    path('main/', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.http import response
from django.http.response import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
# imports
from django import forms
import json
from main.helpers import assemble, outToJson
import os
import subprocess

def index(request):
    '''
    main route
    code to send json data to the frontend
    '''

    return render(request, "main/index.html",{
        "codein" : 1
    })

def write(request):
    '''
    route to get code, process and run it with in the verilog module
    '''

    if request.method == 'POST':
        filename = "assemblycode.asm"       # auxilary file to store instructions
        outfilepath = "simpleComputer/program.v"
        add_code = request.POST.get('code', None)   # get form data
        if add_code is not None:                    # and write it to the auxilary file
            with open(filename, 'w') as file:
                file.write(add_code)

            # convert the instructions to verilog module form to run it
            # returns -1 if instructions are invalid
            if assemble(filename, outfilepath) == -1:
                return HttpResponse('<a href="/main/"> <h1>Oops!! something went wrong with the code</h1> </a>')
        
        # os.system(cmd)
        os.system(f'iverilog -I simpleComputer -o simpleComputer/a.out simpleComputer/program.v')
        # os.system(f'vvp simpleComputer/a.out | python3 simpleComputer/processop.py')


        returnfile = 'process.json'     # file which will hold resulting json data which will be sent back to the interface

        # run the out file from previous step using vvp and write the result to a file for next step
        os.system(f'vvp simpleComputer/a.out > jsoninput.txt')
        # convert the raw data from previous step to json format.
        outToJson('jsoninput.txt', returnfile)


        # read the json file and convert the data to json object
        jsondata = ""
        with open(returnfile, "r") as file:
            jsondata = file.read()

        jsondata = json.loads(jsondata)
        jsondata = str(jsondata)

        # assembly code entered by the user...
        asmcode = ""
        with open("assemblycode.asm", "r") as file:
            asmcode = file.read()
        
        asmcode = json.dumps({
            "asmcode": asmcode
        })

        return render(request, "main/index.html", {
            "codein" : 0,               # set state(not taking any input, displaying the output)
            "jsondata": jsondata,           # json data containing execution sequence
            "asmcode": asmcode              # code entered by the user
        })
        

main/templates/main/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Basic Computer</title>
        <link href="{% static 'main/main.css' %}" rel="stylesheet" type="text/css">
    </head>

    <body>
        <h1>heading</h1>

        <section id="container1">

            {% if codein %}
            <!-- display this if we need to get code from the input text area -->
            <form id="code" action="{% url 'main:write' %}" method="post">
            {%csrf_token%}
            <textarea name="code"
                rows="26"
                cols="50"
                onfocus="this.select()"
                style="font-size: 20px; font-family: monospace;"><-- code goes here --></textarea>
                <br><br>
            <input type="submit" value="Submit">
            </form>

            {% else %}
            <!-- display this part if code is submitted through input -->
            <section id="codeblock">

            <div id="codedisplay" style="width:650px; height:650px ;  line-height: 0.5ch; overflow: scroll;"></div>

            <br><br>
            <button onclick="next()"> next </button>
            <a href="/main/">
            <div style="width: 40px; height: 20px; background-color: mediumspringgreen;">back</div></a>

            </section>
            {% endif %}

            <div id="blockDiag">

                <div id="blockleft">
                    <div id="clk" style="flex: 1;">
                        <div style="position:relative; text-align: center; width:80%; height:80%; background-color:pink;  margin:auto; border:1px solid gray; line-height: 0px;">
                            <p class="blkheading"> Clock </p>
                            <p class="blktext"> _|‾|_|‾ </p>
                        </div>
                    </div>
                    <div id="mar" style="flex: 1; ">
                        <div style="position:relative; text-align: center; width:80%; height:80%; background-color:pink; margin:auto; border:1px solid gray; line-height: 0px;">
                            <p class="blkheading"> Mem address reg </p>
                            <p class="blktext" id="marVal"> 00h </p>
                        </div>
                    </div>
                    <div id="ram" style="flex: 1;">
                        <div style="position:relative; text-align: center; width:80%; height:80%;  background-color:pink; margin:auto; border:1px solid gray; line-height: 0px;">
                            <p class="blkheading"> RAM </p>
                            <p class="blktext" id="ramVal"> 00h </p>
                        </div>
                    </div>
                    <div id="instReg" style="flex: 1; ">
                        <div style="position:relative; text-align: center; width:80%; height:80%; background-color:pink; margin:auto; border:1px solid gray; line-height: 0px;">
                            <p class="blkheading"> Instruction Reg </p>
                            <p class="blktext" id="instRegVal"> 00h </p>
                        </div>
                    </div>
                    <div id="cu" style="flex: 1; ">
                        <div style="position:relative; text-align: center; width:80%; height:80%; background-color:pink; margin:auto; border:1px solid gray; line-height: 0px;">
                            <p class="blkheading"> Control Unit </p>
                            <p class="blktext" id="cuVal"> 00h </p>
                        </div>
                    </div>
                </div>

                <div id="bus">
                    <div style="width:70%; height: 100%; margin: auto; background-color: blueviolet; writing-mode: vertical-lr; text-orientation: upright;">
                    <p style="position:relative; top:40%;"> || BUS || </p>
                    </div>
                </div>

                <div id="blockright">
                    <div id="pc" style="flex: 1; ">
                        <div style="position:relative; text-align: center; width:80%; height:80%; background-color:pink; margin:auto; border:1px solid gray; line-height: 0px;">
                            <p class="blkheading"> Program Counter </p>
                            <p class="blktext" id="pcVal"> 00h </p>
                        </div>
                    </div>
                    <div id="aReg" style="flex: 1; ">
                        <div style="position:relative; text-align: center; width:80%; height:80%; background-color:pink; margin:auto; border:1px solid gray; line-height: 0px;">
                            <p class="blkheading"> A-Resister </p>
                            <p class="blktext" id="aRegVal"> 00h </p>
                        </div>
                    </div>
                    <div id="alu" style="flex: 1; ">
                        <div style="position:relative; text-align: center; width:80%; height:80%; background-color:pink; margin:auto; border:1px solid gray; line-height: 0px;">
                            <p class="blkheading"> ALU </p>
                            <p class="blktext" id="aluVal"> 00h (+)</p>
                        </div>
                    </div>
                    <div id="bReg" style="flex: 1; ">
                        <div style="position:relative; text-align: center; width:80%; height:80%; background-color:pink; margin:auto; border:1px solid gray; line-height: 0px;">
                            <p class="blkheading"> B-Register </p>
                            <p class="blktext" id="bRegVal"> 00h </p>
                        </div>
                    </div>
                    <div id="outReg" style="flex: 1; ">
                        <div style="position:relative; text-align: center; width:80%; height:80%; background-color:pink; margin:auto; border:1px solid gray; line-height: 0px;">
                            <p class="blkheading"> Output Register </p>
                            <p class="blktext" id="outRegVal"> 00h </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </body>

    <script>
        function getCode(){
            // gets code from the input text field
            const elem = document.getElementById('code');
            var text = elem.value;
        }
        
        function highlightBlk(blockid, prop) {
            // function to highlight a block
            // var prevProp;
            // const elem = document.getElementById(blockid).firstElementChild;
            // const elem = document.getElementById(blockid);
            const elem = blockid;
            // prevProp = [elem.style.border, elem.style.backgroundColor];
            elem.style.border = prop[0];
            elem.style.backgroundColor = prop[1];
            // return prevProp;
        }

        var currcycle = 0;      // variable to hold the current state being executed(json index)
        var currInstBlk;
        var instBlkStack = [];
        function next(){
            /*
                returns the next operations to be performed
                called when the next button is pressed
            */

            if(currcycle == 0) {
                // if its the first time, initialize the variable to first element
                currInstBlk = document.getElementById("codedisplay").firstElementChild;
            }

            else if(currcycle + 1 >= Object.keys(text.process).length ){
                // if all operations done, do nothing
                console.log("done");
                return;
            }

            // else get next operation from the json object and return it
            currcycle++;

            currInstBlk.style.backgroundColor = "";             // unset background color of current block
            currInstBlk = currInstBlk.nextElementSibling;       // get next block
            currInstBlk.style.backgroundColor = "hotpink";      // and highlight it

            while(instBlkStack.length > 0){
                var elem = instBlkStack.pop();
                highlightBlk(elem, ["", ""]);
            }

            // printing next set of instructions
            for(var elem in text.process[currcycle]){
                console.log(text.process[currcycle][elem]);

                // de-highlight current active blocks
                var instStr = text.process[currcycle][elem];
                instStr = instStr.split(" ");
                var activeBlk = document.getElementById(instStr[0]);
                instBlkStack.push(activeBlk);

                if(instStr[1] == "r"){
                    // update the value of the block
                    const textValue = document.getElementById(instStr[0] + "Val");
                    textValue.innerHTML = instStr[2];
                    // highlight the block as being read
                    highlightBlk(activeBlk, ["lightblue", "red"]);
                }
                else if(instStr[1] == "w") {
                    // get value of the block and update it
                    const textValue = document.getElementById(instStr[0] + "Val");
                    textValue.innerHTML = instStr[2];
                    // highlight the block as being writen
                    highlightBlk(activeBlk, ["hotpink", "green"]);
                }
            }
        }

        var text = "{{jsondata|safe}}";              // get json string from backend
        function jsonprint(){
            // prints the operations to the display block

            text = text.split("'").join('"');       // replace ' with " in the string(json.parse works without errors)
            text = JSON.parse(text);                //convert to json object

            const codeblk = document.getElementById("codedisplay");
            for(var i in text.process){
                const cycleDiv = document.createElement("div");
                cycleDiv.style.padding = "4px";
                for(var stage in text.process[i]){
                    var strtxt = text.process[i][stage];
                    const codetxt = document.createElement("p");
                    const node = document.createTextNode(strtxt);
                    codetxt.appendChild(node);
                    cycleDiv.appendChild(codetxt);
                }
                codeblk.appendChild(cycleDiv);
            }

            // var asmcode = "{{asmcode}}";
            // insert code entered by the user
            // asmcode = asmcode.split("'").join('"');
            // asmcode = JSON.parse(asmcode);
            // const node = document.createTextNode(asmcode);
            // codeblk.appendChild(node);
        }

        var flg = "{{codein}}";
        if(flg == 0){
            jsonprint();
        }

        // getting sequence of events from the backend

        // element to insert processed sequence
        // const codeblk = document.getElementById("codedisplay");

        // append each element of the json object into the block
        // for(var i in text.process){
        //     for(var stage in text.process[i]){
        //         var strtxt = text.process[i][stage];
        //         const codetxt = document.createElement("p");
        //         const node = document.createTextNode(strtxt);
        //         codetxt.appendChild(node);
        //         codeblk.appendChild(codetxt);
        //     }
        // }

        // // insert code entered by the user
        // var asmcode = "{{asmcode}}";
        // const node = document.createTextNode(asmcode);
        // codeblk.appendChild(node);
    </script>

</html>